### ISSUE TITLE
Envio de NFC-e por e-mail

### ISSUE THREAD

**Issue by ianclever** [nfephp-org/sped-mail#24]
Bom dia,
Conforme a própria documentação do nfephp diz, o envio de e-mail só está habilitado para NFe, venho aqui para solicitar que vocês adicionem essa funcionalidade. O que acham é viável?

Enquanto isso eu vou improvisar no meu ambiente local, para fazer isso funcionar.

NOTA: Eu solicitei isso no link da API nfephp, mas fui informado lá só serão adicionadas correções, o que pode ser visto nesse link:
https://github.com/nfephp-org/nfephp/issues/892

Já observei os códigos das novas subdivisões do antigo nfephp e pelo que pude notar é aqui que vai ficar a parte de envio de e-mail agora, então eu acho que esse é o local correto de fazer a solicitação(me corrijam se eu estiver errado).

**Comment by robmachado** [comment]
Sim esse é provavelmente o melhor local para prover esse recurso. Vamos trabalhar nisso !

**Comment by robmachado** [comment]
O sistema atual já envia NFe, NFCe, CTe, e CCe
