### ISSUE TITLE
Envio de email

### ISSUE THREAD

**Issue by cacio** [nfephp-org/sped-mail#36]
Fiz o composer install desse arquivo para começar os envios de email por meio dele, mas não estou conseguindo enviar ja corrigi varios erros de property que não estavam puxando direito da class stdClass, mas depois de feito isso eu coloco os dados correto e não envia nem com reza braba da esse erro abaixo e não vai.

Warning: Creating default object from empty value in C:\xampp\htdocs\PROJETOS\sped-cte-master\php\cancelamento-exec.php on line 277
Falha: A mensagem não pode ser enviada. Mail Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by robmachado** [comment]
Enviei um email para você através do sped-mail, SEM mexer em absolutamente nada no código disponibilizado

**Comment by cacio** [comment]
Warning: Creating default object from empty value in /home/storage/a/db/6f/prodapro/public_html/sped-mail/examples/testEnvioEmail.php on line 7

Parse error: syntax error, unexpected '.', expecting ']' in /home/storage/a/db/6f/prodapro/public_html/sped-mail/src/Base.php on line 12

Demorei pra responder , mas ta ai só peguei os arquivo gerei o vendor pelo composer install e da esse erro acima

**Comment by cacio** [comment]
Não mexi nada no codigo
