### ISSUE TITLE
Sugestão: assinar digitalmente os e-mails enviados

### ISSUE THREAD

**Issue by guionardo** [nfephp-org/sped-mail#42]
Como o sistema de e-mail utiliza a classe PHPMailer, acredito ser interessante adicionar um grau de confiabilidade na informação enviada ao cliente, ao assinar digitalmente o e-mail.

A função do PHPMailer é a sign() e um exemplo de uso pode ser visto neste [link](https://hotexamples.com/examples/-/PHPMailer/sign/php-phpmailer-sign-method-examples.html).

**Comment by robmachado** [comment]
Humm vou estudar essa possibilidade mas usando o próprio certificado do emitente

**Comment by guionardo** [comment]
Lembrando que o e-mail que consta no certificado deve ser o mesmo que é usado na conta de saída do e-mail.

**Comment by lukBarros** [comment]
Assinar o e-mail digitalmente trás alguma vantagem legal/jurídica, isso parece interessante!

**Comment by robmachado** [comment]
Existem alguns problemas para fazer isso com o PHPMailer (ainda existem alguns BUGS e inconsistências), mas estou ainda vendo como poderia ser feito e qual a real vantagem disso e as consequências que isso poderia acarretar.

**Comment by robmachado** [comment]
A possibilidade assinar digitalmente com o PHPMailer foi inclusa no master
