### ISSUE TITLE
Sugestão: Colocar ID da tag infNFe como nome dos arquivos de anexo

### ISSUE THREAD

**Issue by rabraga** [nfephp-org/sped-mail#46]
Boas!

Quando é usado o sendMail e passado o XML e PDF os arquivos anexados ficam como NFE.XML e NFE.PDF, por exemplo, usando o TYPE do documento.

Seria interessante colocar os nomes dos anexos com o ID da tag infNFe.

Acha possível essa implementação?

Obrigado!

**Comment by robmachado** [comment]
Agora SIM !!!
Sim é perfeitamente possível, pois o XML é lido e podemos montar uma nomenclatura a partir desses dados.
Um pequeno alerta. É impossível saber de que se trata o PDF, então ele receberá um nome baseado no nome do XML.

**Comment by rabraga** [comment]
Ok quanto ao nome do PDF. Sem problemas. 

Vi que em sped-mail/src/mail.php tem getXmlData. Neste momento pode ser lido o ID e setado o nome dos arquivos de anexo.

Certo?

**Comment by robmachado** [comment]
Sim é por ai !

**Comment by robmachado** [comment]
Isso já funciona assim !! não entendo o problema que você enfrenta!! 
Atualize as dependências !!!
