### ISSUE TITLE
Adicionar SMTPAuth e AuthType no parametros de configuração

### ISSUE THREAD

**Issue by rabraga** [nfephp-org/sped-mail#49]
Boas!

Segue uma alteração em mail.php na função loadService. Não está carregando os parâmetros de SMTPAuth e AuthType.

    protected function loadService(\stdClass $config)
    {
        $this->mail->CharSet = 'UTF-8';
        $this->mail->isSMTP();
        $this->mail->Host = $config->host;
        $this->mail->SMTPAuth = true;
        $this->mail->Username = $config->user;
        $this->mail->Password = $config->password;
        $this->mail->SMTPSecure = $config->secure;
        $this->mail->Port = $config->port;
        // inlcuir
        $this->mail->SMTPAuth = $config->SMTPAuth;
        $this->mail->AuthType = $config->AuthType;

        $this->mail->setFrom($config->from, $config->fantasy);
        $this->mail->addReplyTo($config->replyTo, $config->replyName);
    }
Tem servidores de email que só aceita LOGIN no AuthType.

Podem proceder com a alteração?
Obrigado!

**Comment by rabraga** [comment]
Bom dia,

Outros parâmetros também poderiam ser carregados como SMTPDebug e Debugoutput?

Ou a minha solicitação não faz sentido?

Usando a forma abaixo não consigo setar estes parâmetros mesmo colocando eles em $config_email.

Mail::sendMail($config_email, $processar_xml, $arquivo_pdf, $destinatarios, '');

**Comment by rabraga** [comment]
Boas!!!
Será que estou fazendo corretamente? Tive que incluir mais 2 configurações nesta função loadService de mail.php.

        $this->mail->Timeout = $config->Timeout;
        $this->mail->Timelimit = $config->Timelimit;

Existe outra forma de carregar estes parâmetros da PHPMailer sem passar pela função loadService?

**Comment by robmachado** [comment]
Posso até por essa possibilidade de configuração, porem é muito estranho necessitar desse tipo de configuração e as mesmas podem conflitar com as configuração de execução do PHP além de ter outras implicações.

**Comment by rabraga** [comment]
Robson,

Esta configurações de SMTPAuth e AuthType dependem do servidor SMTP, cada um tem o seu. Existe essa configuração no PHP?

No meu caso é melhor ficar na classe do que na configuração do PHP, pois na mesma aplicação eu tenho diversos clientes que usam diferentes servidores de SMTP.

E também precisei incluir o Timeout e Timelimit, pois o default está 300 segundos. Abaixei para 30 segundos.

**Comment by robmachado** [comment]
SMTPAuth e AuthType já estão no config (na ultima atualização do master de hoje) devo incluir também no config os limites de tempo e subo assim que der

**Comment by robmachado** [comment]
Inclusos em MASTER, me avise se estiver OK ai eu crio  a TAG stable

**Comment by rabraga** [comment]
Roberto,
Aqui nos meus testes estão OK.

**Comment by robmachado** [comment]
Obrigado ! no final da tarde gero a TAG stable

**Comment by rabraga** [comment]
Ok! Pode fechar o issue!

**Comment by rabraga** [comment]
Resolvido
