### ISSUE TITLE
phpmailer get_magic_quotes_runtime nova version

### ISSUE THREAD

**Issue by guicalabria** [nfephp-org/sped-mail#57]
Existe alguma exigência da versão 5.2 do phpmailer?
Estou com problemas para versão 7.4 do php para a função get_magic_quotes_runtime
A versão 6 do phpmailer já não utiliza ela.

**Comment by robmachado** [comment]
Essas funções estão DEPRECATED no php7.4

**Comment by robmachado** [comment]
Sempre irá retornar FALSE

**Comment by robmachado** [comment]
É possivel que tenham de ser feitos ajustes para adequar ao PHP7.4 e ao futuro 8.0 (que está chegando)

**Comment by guicalabria** [comment]
no composer da sped-mail está como  "phpmailer/phpmailer": "^5.2",
quer que atualize para a versão 6?

**Comment by robmachado** [comment]
Pode fazer o PR mas teste bem antes de subir o PR para ter certeza que nada irá quebrar
