### ISSUE TITLE
Por que assinar os e-mails com chave?

### ISSUE THREAD

**Issue by eumanito** [nfephp-org/sped-mail#63]
Boa tarde pessoal.

Vi que nesta biblioteca que os e-mails são enviados com o PHPMailer e este script está assinando-os com uma chave .pem

Isso é uma assinatura SSL, certo?

Como o envio é feito através do SMTP, então eu imaginava que isso era automático após configurado o SSL e o DKIN no meu provedor de e-mail. Estou errado?

https://github.com/nfephp-org/sped-mail/blob/29679ea02d33da56adc3ab8db589fb21a38e9968/src/Mail.php#L202-L214

**Comment by robmachado** [comment]
OI ! Manito
O que ocorre é o seguinte o dkin autentica a origem do email para certificar que se originou do domínio correto e não foi forjado.

Já a assinatura cria uma assinatura parecida com a assinatura de uma NFe, que permite a autenticação do CONTEÚDO e não da ORIGEM ( que é feita pelo DKIN).

Roberto

**Comment by eumanito** [comment]
Entendi, obrigado!
